# authors:
# David Hernandez Lopez, david.hernandez@uclm.es

EPSG_TAG = "EPSG"
ENU_TAG = "ENU"
CRS_STRING_SEPARATOR = ";"
ANGULAR_COORDINATES_ACCURACY = 9
LINEAR_COORDINATES_ACCURACY = 4
VERTICAL_ELLIPSOID_TAG = "Ellipsoid"
JSON_DATA_FILE_BASE_NAME = "proj_data_"
LATITUDE_LABEL = "Latitude"
LONGITUDE_LABEL = "Longitude"
ORTHOMETRIC_HEIGHT_LABEL = "Orthometric Height"
ELLIPSOIDAL_HEIGHT_LABEL = "Ellipsoidal Height"
X_PROJECTION_LABEL = "X Projection"
Y_PROJECTION_LABEL = "Y Projection"
X_ECEF_LABEL = "X ECEF"
Y_ECEF_LABEL = "Y ECEF"
Z_ECEF_LABEL = "Z ECEF"
NO_COORDINATE_LABEL = "No value"
CRS_GEODETIC_3D_LABEL = "GEODETIC 3D"
CRS_GEODETIC_2D_LABEL = "GEODETIC 2D"
CRS_ECEF_LABEL = "ECEF"
CRS_VERTICAL_LABEL = "VERTICAL"
CRS_PROJECTED_LABEL = "PROJECTED"
CRS_DIFFERENTIAL_2D_3D_LINEAL_INCREMENT = 100.0 # 1.5 10-5
CRS_DIFFERENTIAL_H_INCREMENT = 0.1 # 1.5 10-5, aprox a 6600 m height
CRS_CONSTANT_JACOBI_SPHERE_RADIUS = 6378137.0
CRS_OPERATION_FROM_OR_TO_VERTICAL_CRS_GETS_LATITUDE_LONGITUDE_AXIS_ORDER = True
LEAST_SQUARES_ADJUSTMENT_CRS_TYPE = CRS_GEODETIC_3D_LABEL
QGIS_CRS_TYPE = CRS_PROJECTED_LABEL

